### ISSUE TITLE
[Update] :Improvement in Login and signup page's input bars

### ISSUE THREAD

**Issue by AnujRathour** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#101]
I want to improve the Login and signup page's input bars and want to make it like in connect with us.  And also twitter logo can be change to X.

**Comment by AnujRathour** [comment]
@gauravsingh1281 I would like to work on this issue . Please assign it to me.

**Comment by gauravsingh1281** [comment]
@AnujRathour assigned 🚀.
