### ISSUE TITLE
Add validation to the forms in login and the contact section

### ISSUE THREAD

**Issue by Daveless** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#102]
In the login form, the user should have a minimum length for the password and the email should have the proper format (example@example.com).
We can also use this kind of validation for the contact section to improve UX.

![image](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/44807207/c0a956c9-1124-40c4-b470-0700474d554a)

**Comment by gauravsingh1281** [comment]
@Daveless assigned 🚀.

**Comment by gauravsingh1281** [comment]
closes via #107
