### ISSUE TITLE
Adding transition effect for the testimonial section

### ISSUE THREAD

**Issue by Acesif** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#105]
Currently, the testimonials cause each segment to snap to the next when pressing the next arrow. 
I would like to make the testimonials have a smooth transition, 
Please assign this issue to me

**Comment by gauravsingh1281** [comment]
@Acesif ?

**Comment by Acesif** [comment]
@gauravsingh1281 Sorry I was a bit busy, I'll make a PR for this issue in a few hours

**Comment by Acesif** [comment]
I noticed that the testimonial section's images were set up by changing the url of each image instead of revolving the whole strip of images. If I try to set up transition effects now, I would need to change a significant portion of the code

**Comment by TarifSadman** [comment]
@gauravsingh1281 can you assign this issue to me? I think I can complete it quickly.

**Comment by gauravsingh1281** [comment]
@TarifSadman Yes go for it 🚀.
