### ISSUE TITLE
Fix mobile layout in the dashboard and also in the main page 

### ISSUE THREAD

**Issue by Daveless** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#111]
There are some layout bugs on the main page and also in the dashboard
![image](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/44807207/d1b8d611-07ba-4bc7-a5d5-64352577e11f)
![image](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/44807207/8fd058a8-123c-489b-8d8a-b2f6f6945873)
![image](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/44807207/b86ee865-c36e-468a-8402-6a68da26e948)
![image](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/44807207/18a06d43-094f-4d18-bd64-8d8a9a383734)

**Comment by gauravsingh1281** [comment]
@Daveless assigned 🚀.

**Comment by P-Jaswanth** [comment]
Hey, I would like to work on this. Could you please assign this for me.

**Comment by gauravsingh1281** [comment]
closes via #112
