### ISSUE TITLE
[FEATURE] : Adding a button to toggle the dark mode. 

### ISSUE THREAD

**Issue by aniketkuma-r** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#113]
Hey @gauravsingh1281 I want to add a feature to toggle into dark mode to the Page. 
Please assign me this issue under Hacktoberfest2023.

Thank You :)

**Comment by gauravsingh1281** [comment]
@aniketkuma-r assigned 🚀.
