### ISSUE TITLE
Make navbar responsive for both Desktop and Mobile view.

### ISSUE THREAD

**Issue by gauravsingh1281** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#21]

**Comment by thezeeshann** [comment]
@gauravsingh1281 assign me. I would like to work on this issue.

**Comment by gauravsingh1281** [comment]
@thezeeshann assigned. Please use Tailwind CSS.

**Comment by thezeeshann** [comment]
@gauravsingh1281 okay

**Comment by ayat0110** [comment]
Hope you're doing good. I saw the issue about creating a responsive navbar with Tailwind on your open-source project. I've got some experience in that area and I'd love to help out.

Could you assign me as a contributor to the repository so I can start working on it? I'm all for making sure the navbar works great on both desktop and mobile.

**Comment by thezeeshann** [comment]
@ayat0110 I'm working on this issue. if you want to contribute you can contribute to any other issue

**Comment by gauravsingh1281** [comment]
@ayat0110 Hey you can work on another issue. We are creating more issues very soon.

**Comment by gauravsingh1281** [comment]
@thezeeshann Hey how much work has been completed?

**Comment by gauravsingh1281** [comment]
@thezeeshann ?

**Comment by gauravsingh1281** [comment]
Hey @thezeeshann I'm unassigning this issue because you have been inactive for a long time.

**Comment by gauravsingh1281** [comment]
Hey @ayat0110 if you want to work on this issue you can work on it.

**Comment by vashukashyap** [comment]
can I work on this issue?

**Comment by gauravsingh1281** [comment]
@vashukashyap Yes you can work on it. please use Tailwind CSS.
