### ISSUE TITLE
Rentalog Favicon is not visible in production.

### ISSUE THREAD

**Issue by gauravsingh1281** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#22]
<img width="960" alt="Screenshot 2023-07-28 190406" src="https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/85905403/ed39a318-8ea7-4a25-a0c3-fd7938ecd6c3">

**Comment by nakel-ola** [comment]
@gauravsingh1281 can you assign this issue to me.
