### ISSUE TITLE
Design and Create Rentalog user login page.

### ISSUE THREAD

**Issue by gauravsingh1281** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#23]
Take inspiration from [Rentalog.in](https://rentalog-web-app.azurewebsites.net/login) login page.

**Comment by nakel-ola** [comment]
@gauravsingh1281  Is it just the ui that should be created ??

**Comment by gauravsingh1281** [comment]
@nakel-ola First create the login page ui after that if u are able to add page routing you can go for it.

**Comment by nakel-ola** [comment]
ok, assign it to me

**Comment by gauravsingh1281** [comment]
@nakel-ola Before making a pull request, please share the screenshot of the login page you have designed and try to make it more catchy and appealing, according to its homepage. Also, use Tailwind CSS for its responsiveness.

**Comment by nakel-ola** [comment]
@gauravsingh1281 understood.

**Comment by nakel-ola** [comment]
@gauravsingh1281 Is it ok

Mobile:
![mobile](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/109567025/51c371de-41e8-4347-bf04-4f15d57a12ce)

Desktop:
![Rentalog __ Free Rent Management Web App For Landlords](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/109567025/3c9f33d0-b9bf-40ba-9323-38bb5da91ca5)

**Comment by nakel-ola** [comment]
Mobile:
![mobile (2)](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/109567025/05bd296e-f6fb-42b4-90cd-7ce87d6305e8)

**Comment by gauravsingh1281** [comment]
@nakel-ola Hey how much work has been completed?

**Comment by nakel-ola** [comment]
@gauravsingh1281 check this out

Desktop 
![mobile (1)](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/109567025/b65aa602-fd93-4631-9e09-12ac930a602b)

Mobile
![mobile](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/109567025/74727745-87a5-482e-8b2a-b4fc41475033)

**Comment by gauravsingh1281** [comment]
@nakel-ola its look good.

**Comment by gauravsingh1281** [comment]
@nakel-ola ?
