### ISSUE TITLE
Design and Create Rentalog user registration page.

### ISSUE THREAD

**Issue by gauravsingh1281** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#24]
Take inspiration from [Rentalog.in](https://rentalog-web-app.azurewebsites.net/register) Signup Page.

**Comment by rafeyshah** [comment]
Hey there, Do I've to design on my own and create signup page?

**Comment by gauravsingh1281** [comment]
@rafeyshah Yes, you have to first design the signup page and then convert it into code.

**Comment by rafeyshah** [comment]
Perfect, Please assign the issue to me

**Comment by rafeyshah** [comment]
@gauravsingh1281

**Comment by gauravsingh1281** [comment]
@rafeyshah Please try to make it responsive for both mobile and desktop. And use Tailwind CSS.

**Comment by rafeyshah** [comment]
Ah, I used regular css. I was about to pushed the code after making it responsive. Would you mind please take a look? 
I've added some transitions. 
https://www.loom.com/share/2694da508af64229811ecaded9322456?sid=84611855-49a8-45e8-9ee0-0ecb866f0fc7

**Comment by rafeyshah** [comment]
@gauravsingh1281

**Comment by gauravsingh1281** [comment]
@rafeyshah try to make the design more catchy and appealing.

**Comment by gauravsingh1281** [comment]
@rafeyshah Please try to make the registration page design more catchy and appealing. According to the Rentalog homepage.

**Comment by gauravsingh1281** [comment]
@rafeyshah Hey, how much work has been completed?

**Comment by gauravsingh1281** [comment]
@rafeyshah ?

**Comment by gauravsingh1281** [comment]
Hey @rafeyshah  I'm unassigning this issue because you have been inactive for a long time.

**Comment by kcsaiganesh** [comment]
Hey , I can do this , i do have experience in tailwind css, mui.

**Comment by kcsaiganesh** [comment]
@gauravsingh1281  ![image](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/75118214/e2ec0922-0f18-48c1-aea0-f1cbb6b594c1)
I have design with respect to login, if you want me to redesign , Please dont hesitate to feed 🤞.

**Comment by kcsaiganesh** [comment]
Dear Gauravsingh,

I am writing to request that you enable the discussion page for the
Rentalog-Rent-Managment
<https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords>
repository
on GitHub. I believe that enabling discussions would be a valuable addition
to the repository, as it would allow users to ask questions, share ideas,
and collaborate on the project.

Here are some of the benefits of enabling discussions:

Improved communication: Discussions provide a central place for users to
communicate with each other about the repository. This can help to improve
communication and collaboration between users.
Reduced support burden: Discussions can help to reduce the support burden
on the repository owners and maintainers. By enabling discussions, users
can help each other with questions and problems, which can free up the
repository owners and maintainers to focus on other tasks.
Increased community engagement: Discussions can help to increase community
engagement with the repository. By providing a forum for users to
communicate and collaborate, discussions can help to make the repository
more welcoming and inclusive.
I believe that enabling discussions would be a positive change for the
[Repo Name] repository. I hope that you will consider my request.

Thank you for your time and consideration.

Sincerely,
Kc Sai Ganesh

**Comment by gauravsingh1281** [comment]
Thanks for your suggestion Kc Sai Ganesh.
I have added the discussion option in the Rentalog Repo on GitHub.
