### ISSUE TITLE
Design and Create Rentalog Admin Dashboard. 

### ISSUE THREAD

**Issue by gauravsingh1281** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#25]
### Take Inspiration From [Rentalog.in](https://rentalog-web-app.azurewebsites.net/dashboard) Admin Dashboard.

<img width="956" alt="Screenshot 2023-07-28 191846" src="https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/85905403/29feb6ee-fd19-4e0b-8304-08d09aa3d2e3">

**Comment by Kashif-Saleem-Ghuman** [comment]
@gauravsingh1281 May I work on this issue?

**Comment by gauravsingh1281** [comment]
@Kashif-Saleem-Ghuman Yes you can work on it. You have to redesign the Rentalog admin dashboard.

**Comment by Kashif-Saleem-Ghuman** [comment]
@gauravsingh1281 Sure, I will do it!

**Comment by Kashif-Saleem-Ghuman** [comment]
![desktop-view-form](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/111677605/c15d3bd4-301b-4d3b-8a5e-7cd2965a1c3c)
@gauravsingh1281 Hi,

Hope you are doing well!

- On the main branch, things are messed up. The Contact Us Section part I did is messed up. Here is a screenshot of the messed-up one:

![new01](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/111677605/29376972-63c1-4554-8ce7-796dc5b18877)
![new02](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/111677605/652c94f9-aac1-4c47-90b4-bb50e1fe032b)

- The section above the form has been removed, the form itself is messed up

- These are the screenshots from my branch:
[screenshots.pdf](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/files/12304337/screenshots.pdf)

**Comment by gauravsingh1281** [comment]
Hey @Kashif-Saleem-Ghuman Everything is fine on main branch please refresh your branch.

Deployment Preview Link of main Branch - https://visionary-fenglisu-db1b1d.netlify.app/

**Comment by Kashif-Saleem-Ghuman** [comment]
@gauravsingh1281 Hey, I replied directly to the email. I will push the changes tomorrow

**Comment by gauravsingh1281** [comment]
@Kashif-Saleem-Ghuman Ok

**Comment by gauravsingh1281** [comment]
@Kashif-Saleem-Ghuman ?

**Comment by Kashif-Saleem-Ghuman** [comment]
Apologies for the delay @gauravsingh1281 
I will submit it tomorrow

**Comment by gauravsingh1281** [comment]
Hii @Kashif-Saleem-Ghuman  I'm unassigning this issue because you have been inactive for a long time.

**Comment by Kashif-Saleem-Ghuman** [comment]
Hi @gauravsingh1281 Brother I apologise once again
However, the main task was complete, only the nav colour issue was left to be resolved

**Comment by vashukashyap** [comment]
can i help in this, issue?

**Comment by gauravsingh1281** [comment]
@vashukashyap yes. Please take inspiration from rentalog figma design.

**Comment by vashukashyap** [comment]
@gauravsingh1281 sir, i have created the dashboard with new design!..

# Desktop
![Screenshot from 2023-10-22 05-52-10](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/129667408/66f2e6e0-0313-4001-83c3-7088a47e7fec)

# Mobile

![Screenshot from 2023-10-22 05-52-55](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/129667408/2e66c277-369f-4547-be0f-8ae579a05522)

![Screenshot from 2023-10-22 06-04-12](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/129667408/fe602854-33d2-46d7-8b56-61328662f1bd)


after review,
if you are fine with this design, i will submit PR.
moreover, for designing dashboard components and adding authentication system.
can it be done by submitting multiple PR?

**Comment by gauravsingh1281** [comment]
Hii @vashukashyap please refer to rentalog figma design.

**Comment by gauravsingh1281** [comment]
@vashukashyap ?

**Comment by Daveless** [comment]
If this issue has not been solved yet, may I work on this?

**Comment by gauravsingh1281** [comment]
closes via #108
