### ISSUE TITLE
Create toggle Navbar for Mobile view.

### ISSUE THREAD

**Issue by gauravsingh1281** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#37]
Take inspiration from its Figma design - https://www.figma.com/file/9WhtUQT7s5ogTiDTp90PxI/RENTALOG-WEB-DESIGN?type=design&node-id=0-1&mode=design&t=fo01ltksUPD3DKTy-0

**Comment by DannyK05** [comment]
@gauravsingh1281 Can I work on this

**Comment by Tusharrgrg** [comment]
can u assign this to me

**Comment by koyaboy** [comment]
Hi @gauravsingh1281,

I'd be keen to take it on. I've tackled numerous Frontend Mentor projects, and this particular issue seems quite familiar. I'm confident I can handle it efficiently. Looking forward to your response!

**Comment by gauravsingh1281** [comment]
@DannyK05 Yes bro you can work on it. please try to use Tailwind CSS.

**Comment by DannyK05** [comment]
Alright bro 
Thanks

**Comment by gauravsingh1281** [comment]
Hi @DannyK05 This issue has already been resolved by PR #38.
