### ISSUE TITLE
[Updating] Updating navbar links and adding parallax effects and hover effects to buttons.

### ISSUE THREAD

**Issue by rohandol112** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#40]
Updating navbar links and adding parallax effects and hover effects to buttons which are not properly styled.

Assigned me issue as label of hacktoberfest.

**Comment by gauravsingh1281** [comment]
@rohandol112 ?

**Comment by rohandol112** [comment]
i'm working on it @gauravsingh1281 sry for late.

**Comment by gauravsingh1281** [comment]
@rohandol112 ?

**Comment by gauravsingh1281** [comment]
Hii @rohandol112 I'm unassigning this issue because you have been inactive for a long time.

**Comment by SumanKisku** [comment]
@gauravsingh1281 I would love to take on this issue. Can you give me little bit more details about  **Updating navbar links** - what to update, **hover effects to buttons** - which buttons to have hover effects?

**Comment by Abhinav3021** [comment]
@rohandol112  please assign me to this issue
