### ISSUE TITLE
Add hovering template to "Our services includes" section

### ISSUE THREAD

**Issue by pranavsuriya-sr** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#48]
When the mouse pointer is moved over the section's tiles, create a tilt/hovering effect. 

![image](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/91081814/54d36933-b860-44a5-add3-b9d325c91879)

**Comment by Salem2147** [comment]
.

**Comment by Salem2147** [comment]
https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/issues/48#issue-1943064815

**Comment by pratikshelar546** [comment]
can I work on it?
