### ISSUE TITLE
Create our services section for the Rentalog from its figma design.

### ISSUE THREAD

**Issue by gauravsingh1281** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#5]
Figma Design Link - https://www.figma.com/file/9WhtUQT7s5ogTiDTp90PxI/RENTALOG-WEB-DESIGN?type=design&node-id=0-1&mode=design&t=ZNeyPXk16TlWB6I6-0

**Comment by karandeep4423** [comment]
can i work on it @gauravsingh1281 ?

**Comment by gauravsingh1281** [comment]
@karandeep4423 Yes you can work on it.

**Comment by karandeep4423** [comment]
hi, we are working only in frontend part now, site is not responsive at all.

**Comment by karandeep4423** [comment]
could you please reply me?

**Comment by gauravsingh1281** [comment]
@karandeep4423 Hey sorry for the late reply actually I was busy with my college exams. Yes currently we are working only on the frontend part of the site and trying to make it responsive across all devices once the homepage is completed then we start adding the features like user authentication.

**Comment by karandeep4423** [comment]
okay.
