### ISSUE TITLE
Update the background image of the website

### ISSUE THREAD

**Issue by unm07** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#61]
The background image is low quality and hazy. Updating it will give the website a better look.

**Comment by unm07** [comment]
May I work on this?

**Comment by gauravsingh1281** [comment]
@unm07 ?

**Comment by SumanKisku** [comment]
@gauravsingh1281 as the original assignee isn't responding can you assign it to me?

**Comment by gauravsingh1281** [comment]
@SumanKisku assigned 🚀
