### ISSUE TITLE
Create testimonials section for the Rentalog from its figma design.

### ISSUE THREAD

**Issue by gauravsingh1281** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#7]
Figma Design Link - https://www.figma.com/file/9WhtUQT7s5ogTiDTp90PxI/RENTALOG-WEB-DESIGN?type=design&node-id=0-1&mode=design&t=ZNeyPXk16TlWB6I6-0

**Comment by shikham129** [comment]
Can you please assign me this issue ?

**Comment by gauravsingh1281** [comment]
@shikham129 okay try to make this section responsive and use Tailwind CSS.

**Comment by gauravsingh1281** [comment]
@shikham129 Hey how much work has been completed?
