### ISSUE TITLE
docs: update README.md

### ISSUE THREAD

**Issue by beingsie** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#72]
## Brief description of issue
- The current `README.md` file indicates that the stack for this web app contains _Bootstrap_ though it uses **_Tailwind CSS_**.

### Resolution:
- Update `README.md` to display **Tailwind CSS** instead of Bootstrap.

**Comment by gauravsingh1281** [comment]
Hii @beingsie thank you for your contribution. But the tech stack which is written in readme is the tech stack of its current version. https://rentalog-web-app.azurewebsites.net/ and this repo is for its migration to react js, next js, and tailwind CSS.
