### ISSUE TITLE
Ḥover effect on buttons

### ISSUE THREAD

**Issue by PCoder23** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#78]
I noticed there is no hover effect on buttons on home page , would you like me to work on it under hacktoberfest ?

**Comment by gauravsingh1281** [comment]
> I noticed there is no hover effect on buttons on home page , would you like me to work on it under hacktoberfest ?

Hii @PCoder23 yes please proceed 😇

**Comment by gauravsingh1281** [comment]
Closes via #79
