### ISSUE TITLE
Create contact us section for the Rentalog from its figma design.

### ISSUE THREAD

**Issue by gauravsingh1281** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#8]
Figma Design Link - https://www.figma.com/file/9WhtUQT7s5ogTiDTp90PxI/RENTALOG-WEB-DESIGN?type=design&node-id=0-1&mode=design&t=ZNeyPXk16TlWB6I6-0

**Comment by Kashif-Saleem-Ghuman** [comment]
@gauravsingh1281 What about this one, shall I work on this?

**Comment by gauravsingh1281** [comment]
@Kashif-Saleem-Ghuman Yes you can work on this.

**Comment by gauravsingh1281** [comment]
@Kashif-Saleem-Ghuman Hey how much work has been completed?

**Comment by Kashif-Saleem-Ghuman** [comment]
@gauravsingh1281 Hi, It is almost done. Just finishing the contact form. Will open a PR tomorrow. Thanks for your patience.

**Comment by Kashif-Saleem-Ghuman** [comment]
@gauravsingh1281 Infact let me just open the PR now, but I will ask you for a review tomorrow when it is completed.
