### ISSUE TITLE
The Navbar can have nice hovering effects while surfing through your website..

### ISSUE THREAD

**Issue by SaiSantosh2209** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#81]
![image](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/83724995/4f95e0c2-edcf-4329-9a11-dab2aee4eb74)

**Comment by tutrinh16** [comment]
Hey there! Can you assign me.

**Comment by gauravsingh1281** [comment]
closes via 85
