### ISSUE TITLE
The Images in the "MY SERVICES" section can be improvised , like adding zoom in feature while hovering it...

### ISSUE THREAD

**Issue by SaiSantosh2209** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#82]
![image](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/83724995/9bfb97fe-1531-4620-ad40-e46b970c9e38)

**Comment by gauravsingh1281** [comment]
Closes via #86
