### ISSUE TITLE
Interactive "Get Started" button ...

### ISSUE THREAD

**Issue by SaiSantosh2209** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#83]
![image](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/83724995/350fd2ca-4113-4d9c-90d1-42c80d1a6962)

**Comment by gauravsingh1281** [comment]
Hi @SaiSantosh2209 please give some more details about this issue.

**Comment by gauravsingh1281** [comment]
@SaiSantosh2209 ?

**Comment by SaiSantosh2209** [comment]
Hello 👋  , I just wanted to make the button more interactive while selecting or hovering it ..

**Comment by auth-02** [comment]
@gauravsingh1281 is this issue still active, would like to work on this?
