### ISSUE TITLE
Deceptive Site Warning on rentalog-web-app.azurewebsites.net

### ISSUE THREAD

**Issue by Uzo-Felix** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#91]
I am receiving a "Deceptive site ahead" warning when attempting to access the website at "rentalog-web-app.azurewebsites.net." The warning states that attackers may attempt to trick users into installing software or revealing personal information. This warning has raised concerns about the safety and security of the website.

screenshot

![Hacktoberfest](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/120843233/181b13e7-9b5d-4406-995e-139d6e61e0e5)

**Comment by gauravsingh1281** [comment]
Hi @Uzo-Felix thank you for showing your interest in rentalog but this warning is not coming on this site. This warning comes on the original repo of rentalog.in which is not open for contribution.
