### ISSUE TITLE
Restructuring the Contact Section

### ISSUE THREAD

**Issue by pabitra-kumar** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#92]
For Contact section,
Informal Content: 
The content in the contact section lacks a formal tone and language, which may not align with the professional image the website intends to project.

Fields and Text Alignment: 
Fields and accompanying text are not displayed side by side as is typical on formal websites. This can make the contact form appear disorganized and use

![Screenshot 2023-10-24 092538](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/assets/98006358/5ec13b46-5620-4f60-bdaa-4acce00add08)

**Comment by pabitra-kumar** [comment]
@gauravsingh1281 
Review the PR and give Relevant comments.

**Comment by gauravsingh1281** [comment]
Closes via #94 PR
