### ISSUE TITLE
Which page or section the user is currently on when they click on a navigation link

### ISSUE THREAD

**Issue by weberankit** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#93]
I want to enhance the user experience by making it clear which page or section the user is currently on when they click on a navigation link.

how I am going to do that ??
since this project uses react-router-dom I am going to use Use-current location to find URL text and on that basis, I will change the background color of that nav link

could you assign me this task under the Hactoberfest tag?

**Comment by gauravsingh1281** [comment]
Hi @weberankit choose color which match with the homepage theme.

**Comment by pratikshelar546** [comment]
@weberankit can work on this because there has been no update for 2 days

**Comment by weberankit** [comment]
@gauravsingh1281 plz check pr #104

**Comment by gauravsingh1281** [comment]
Closes via #104
