### ISSUE TITLE
Improving ui in the page 

### ISSUE THREAD

**Issue by jeet1703** [gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords#97]
I would like to change the navbar animation and redesign the login / signup button and also improve the transition in the whole page please assign me this issue

**Comment by gauravsingh1281** [comment]
@jeet1703 yes please proceed 🚀.

**Comment by SumanKisku** [comment]
@jeet1703 hi how is your work going? If you don't mind can we work together on this issue?

**Comment by gauravsingh1281** [comment]
closes via #118
